'use client';
import React from 'react';
import './styles/globals.css';
// import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Theme, ThemePanel } from '@radix-ui/themes';
import SideBar from './layout/Sidebar';
import { ThemeProvider } from 'next-themes';
import { persistor, store } from '@/store/app';
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import SimpleTextLoading from './layout/SimpleTextLoading';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={'h-screen'} style={inter.style}>
        <Provider store={store}>
          <PersistGate loading={<SimpleTextLoading />} persistor={persistor}>
            <ThemeProvider attribute="class">
              <Theme accentColor="blue" grayColor="sand" radius="large" scaling="95%">
                <div className="flex h-screen w-screen">
                  <SideBar />
                  {children}
                </div>
                <ThemePanel />
              </Theme>
            </ThemeProvider>
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
